spring.application.name=springboot_10_user_board

#TODO 003 Spring Boot에서 필요한 환경 설정
# 필수 : logback profile 설정, Datasource, mybatis mapper위치, mybatis DTO Alias
# 추가 : Thymeleaf 캐쉬, 인코딩

spring.profiles.active=dev

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521
spring.datasource.username=EDU
spring.datasource.password=EDU

mybatis.type-aliases-package=com.min.edu.vo
mybatis.mapper-locations=classpath:sqls/*.xml
