spring.application.name=spring_jpa

#TODO 002 Database 연결을 위한 application.properties 작성

# MySql 접속 정보(URL, class(생략가능-부트에서 자동인식), 계정, 비밀번호)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/test?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=test
spring.datasource.password=

# JPA 전략
# none : 아무것도 하지 않음
# create-drop : 프로젝트 시작시 생성, 종료시 삭제(테스트용)
# create: 기존 테이블을 삭제 후 새로 생성
# update: 변경된 스키마를 자동으로 반영
# validate : 매핑된 엔터티(JAVA객체)와 DB 스키마를 검증
spring.jpa.hibernate.ddl-auto=create-drop

# Hibernate에 의해서 생성된 SQL문을 볼 수 있도록 설정
spring.jpa.show-sql=true

# DB에 맞는 SQL을 생성하기 위한 Dialect(생략가능)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

#예외처리 메시지를 postman 에서 보기 위한 설정
spring.web.error.include-message=always


# =========================
# MyBatis + JPA 하이브리드 설정
#
# 사용 영역
# 단순 CRUD - JPA
# JOIN, 성능튜닝, 페이징/통계 - MyBatis 
# =========================
# mybatis.mapper-locations=classpath:mapper/**/*.xml
# mybatis.type-aliases-package=com.example.domain






