spring.application.name=Springboot_Security

#TODO 005 application.properties 작성

# allowPublicKeyRetrieval=true  보안접속 방식
# useSSL=false                  보안접속 방식
# serverTimezone=Asia/Seoul     서버타임존(클라우드, Docker 사용할때)
# characterEncoding=UTF-8       인코딩

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=test
spring.datasource.password=

#JPA 전략
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true



#옵션
spring.web.error.include-message=always

