spring.application.name=practice07

server.port=8081

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=EDU
spring.datasource.password=EDU

mybatis.type-aliases-package=com.min.edu.vo

mybatis.mapper-location=classpath:sqls/*.xml


spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8