spring.application.name=springboot_04_mybatis

#TODO 003 Datasource의 정보를 설정
#SpringBoot Starter에 자동으로 값을 바인딩해주기 때문이다

#Datasource : DBCP -> DBCP2 ->SpringBoot는 기본 HikariCP으로 되어 있다
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=EDU
spring.datasource.password=EDU

## TODO 005 myBatis에서 사용 DTO/VO객체의 Alias 설정
##MyBatis의 Alias는 SpringBoot에서 자동으로 Camal 방식으로 사용하면 된다
## EmpVo => empVo로 사용하면 된다
## 만약에 사용되는 이름을 사용자변경하고 싶다면 Class 위해 @Alias("")
## 패키지가 다른 경우 
mybatis.type-aliases-package=com.min.edu.dto

## TODO myBatis에서 xml mapper 사용하는 방법
mybatis.mapper-locations=classpath:sqls/*.xml

## myBatis 로그 처리 => 기본 로그 => logback-spring.xml 사용하게 된다 => logback.xml 파일명을 변경하면 된다
logging.level.org.mybatis=DEBUG
logging.level.org.apache.ibatis=DEBUG

## myBatis 로그 + 쿼리 결과 로그로 출력하고 싶을 때(교육용 혹은 JUnit)
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

##------------------------------------------------------
# TODO 502 DispatcherServlet 에 의해서 작성된 ViesResolver => Spring Container(@Controller)에서 반환된 문자열을 화면에 요청으로 처리
#							UrlBaseViewResolver 

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

##TODO 503 Spring Container로 전달되는 Encoding 처리
## 예전버전 : server.servlet.encoding.charset=UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true

#Spring devtools에 의해서 변경사항이 자동적이 된다
#Spring Boot 동작되고 있는 상태일때 JSP가 변경되지 않는다 그래서 설정을 통해서 변경이 적용될 수 있도록 해준다
server.servlet.jsp.init-parameters.development=true











